version: '3.9'
services:
  mysql:
    image: mysql:5.7.33
    restart: always
    container_name: mysql-bloonstl-server
    ports:
      - '3310:3306'
    volumes:
      - mysql-bloonstl-data:/var/lib/mysql
      - ./lib/mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'bloonstl'
      MYSQL_USER: 'bloonstl'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'admin123'

volumes:
  mysql-bloonstl-data:
    name: bloonstl-mysql-data
